; autogenerated by ./scripts/aseprite-export.sh
{
:warn (let [img (love.graphics.newImage "assets/export-warn.png")] (img:setFilter :nearest :nearest) {: img :width (img:getWidth) :height (img:getHeight)}) 
:spawn (let [img (love.graphics.newImage "assets/export-spawn.png")] (img:setFilter :nearest :nearest) {: img :width (img:getWidth) :height (img:getHeight)}) 
}
